=== splunk/security_content/spec/v2/baselines.spec.json
{
  "$id": "https://api.splunkresearch.com/schemas/baselines.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "phantom": {
      "properties": {
        "phantom_server": {
          "description": "IP address and username of the phantom server. Currently, we will ship this value as automation (hostname) and we encourage the users to modify those values according to their environment. Eg: automation (hostname)",
          "examples": [
            "automation (hostname)"
          ],
          "type": "string"
        },
        "playbook_name": {
          "description": "Name of the playbook. This name should be the same as the name on phantom community repository on github with underscores and appended with community/<playbook_name>. The playbooks are hosted on https://github.com/phantomcyber/playbooks. Eg: community/simple_network_enrichment",
          "examples": [
            "community/dns_hijack_investigation"
          ],
          "type": "string"
        },
        "playbook_url": {
          "description": "Url of the playbook on Phantom website.",
          "examples": [
            "https://my.phantom.us/4.1/playbook/dns-hijack-investigation/"
          ],
          "type": "string"
        },
        "schedule": {
          "description": "Various fields to assist in scheduling the search",
          "properties": {
            "cron_schedule": {
              "description": "Schedule of the search in cron format",
              "examples": [
                "0 * * * *"
              ],
              "type": "string"
            },
            "earliest_time": {
              "description": "The earliest time the search should run in Splunk format",
              "examples": [
                "-70m@m"
              ],
              "type": "string"
            },
            "latest_time": {
              "description": "The latest time tes search should run against in Splunk format",
              "examples": [
                "-10m@m"
              ],
              "type": "string"
            }
          },
          "type": "object"
        },
        "sensitivity": {
          "description": "TLP colors (White, Green, Amber or Red)",
          "examples": [
            "green"
          ],
          "type": "string"
        },
        "severity": {
          "description": "Severity in phantom (High, Medium, Low)",
          "examples": [
            "medium"
          ],
          "type": "string"
        }
      },
      "required": [
        "phantom_server",
        "playbook_name",
        "playbook_url"
      ],
      "type": "object"
    },
    "splunk": {
      "properties": {
        "schedule": {
          "description": "Various fields to assist in scheduling the search",
          "properties": {
            "cron_schedule": {
              "description": "Schedule of the search in cron format",
              "examples": [
                "0 * * * *"
              ],
              "type": "string"
            },
            "earliest_time": {
              "description": "The earliest time the search should run in Splunk format",
              "examples": [
                "-70m@m"
              ],
              "type": "string"
            },
            "latest_time": {
              "description": "The latest time tes search should run against in Splunk format",
              "examples": [
                "-10m@m"
              ],
              "type": "string"
            }
          },
          "type": "object"
        },
        "lookups": {
          "description": "A list of lookups in the search",
          "examples": [
            "detection_search_lookup"
          ],
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "macros": {
          "description": "A list of macros in the search",
          "examples": [
            "detection_search_output_filter"
          ],
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "search": {
          "description": "The search (in SPL) executed within core Splunk for investgation.",
          "examples": [
            "| inputlookup discovered_dns_records.csv | rename answer as discovered_answer | join domain[|tstats summariesonly=true count values(DNS.record_type) as type, values(DNS.answer) as current_answer values(DNS.src) as src from datamodel=Network_Resolution where DNS.message_type=RESPONSE DNS.answer!=\"unknown\" DNS.answer!=\"\" by DNS.query | rename DNS.query as query | where query!=\"unknown\" | rex field=query \"(?<domain>\\w+\\.\\w+?)(?:$|/)\"] | makemv delim=\" \" answer |  makemv delim=\" \" type | sort -count | table count,src,domain,type,query,current_answer,discovered_answer | makemv current_answer  | mvexpand current_answer | makemv discovered_answer | eval n=mvfind(discovered_answer, current_answer) | where isnull(n)"
          ],
          "type": "string"
        }
      },
      "required": [
        "search",
        "schedule"
      ],
      "type": "object"
    }
  },
  "description": "The fields that make up the manifest of a version 2 baseline search",
  "properties": {
    "baseline": {
      "anyOf": [
        {
          "required": [
            "splunk"
          ]
        },
        {
          "required": [
            "phantom"
          ]
        }
      ],
      "properties": {
        "phantom": {
          "$ref": "#/definitions/phantom"
        },
        "splunk": {
          "$ref": "#/definitions/splunk"
        }
      },
      "type": "object"
    },
    "creation_date": {
      "description": "The date the baseline manifest was created",
      "examples": [
        "2019-02-14"
      ],
      "type": "string"
    },
    "data_metadata": {
      "description": "Information about the date being ingested",
      "properties": {
        "data_eventtypes": {
          "description": "A list of eventtypes, if any, used by this search",
          "examples": [
            "wineventlog"
          ],
          "items": {
            "type": "string"
          },
          "minItems": 0,
          "type": "array",
          "uniqueItems": true
        },
        "data_models": {
          "description": "A list of data models, if any, used by this search",
          "examples": [
            "Network_Resolution"
          ],
          "items": {
            "enum": [
              "Alerts",
              "Application_State",
              "Authentication",
              "Certificates",
              "Change_Analysis",
              "Change",
              "Cloud_Infrastructure",
              "Malware",
              "Email",
              "Identity_Management",
              "Network_Resolution",
              "Network_Traffic",
              "Vulnerabilities",
              "Web",
              "Network_Sessions",
              "Updates",
              "Risk",
              "Endpoint"
            ]
          },
          "minItems": 0,
          "type": "array",
          "uniqueItems": true
        },
        "data_source": {
          "description": "A high-level description of the type of data needed for this search to complete",
          "examples": [
            "DNS"
          ],
          "items": {
            "type": "string"
          },
          "minItems": 0,
          "type": "array",
          "uniqueItems": true
        },
        "data_sourcetypes": {
          "description": "The list of sourcetypes, if any, used by this search",
          "examples": [
            "stream:dns"
          ],
          "items": {
            "type": "string"
          },
          "minItems": 0,
          "type": "array",
          "uniqueItems": true
        },
        "providing_technologies": {
          "description": "A list of technologies that provide this data",
          "examples": [
            "Bro"
          ],
          "items": {
            "enum": [
              "Apache",
              "AWS",
              "Azure",
              "Bro",
              "GCP",
              "Microsoft Windows",
              "Linux",
              "macOS",
              "Netbackup",
              "Splunk Enterprise",
              "Splunk Enterprise Security",
              "Splunk Stream",
              "Active Directory",
              "Bluecoat",
              "Carbon Black Response",
              "Carbon Black Protect",
              "CrowdStrike Falcon",
              "Microsoft Exchange",
              "Nessus",
              "Palo Alto Firewall",
              "Qualys",
              "Sysmon",
              "Tanium",
              "Ziften",
              "Censys",
              "Passive Total",
              "WHOIS"
            ]
          },
          "minItems": 0,
          "type": "array",
          "uniqueItems": true
        }
      },
      "required": [
        "data_source",
        "providing_technologies"
      ],
      "type": "object"
    },
    "description": {
      "description": "A description of what the search is is doing to create a baseline",
      "examples": [
        "The search takes corporate and common cloud provider domains configured under `cim_corporate_email_domains.csv`, `cim_corporate_web_domains.csv`, and `cloud_domains.csv` finds their responses across the last 30 days from data in the `Network_Traffic` datamodel, then stores the output under the `discovered_dns_records.csv` lookup"
      ],
      "type": "string"
    },
    "eli5": {
      "description": "Explain it like I am 5 - A detail description of the SPL of the search, written in a style that can be understood by a future Splunk expert",
      "examples": [
        "Discover the DNS records and their answers for domains owned by the company using network traffic events. The discovered events are exported as a lookup named `discovered_dns_records.csv`"
      ],
      "type": "string"
    },
    "entities": {
      "description": "A list of entities that will used in the story flow or are relevant to the security investigation.",
      "examples": [
        "dest",
        "user"
      ],
      "items": {
        "enum": [
          "accessKeyId",
          "arn",
          "awsRegion",
          "bucketName",
          "City",
          "Country",
          "dest_port",
          "dest",
          "event_id",
          "instanceId",
          "message_id",
          "networkAclId",
          "process_name",
          "process",
          "recipient",
          "Region",
          "region",
          "resourceId",
          "session_id",
          "src_ip",
          "src_mac",
          "src_user",
          "src",
          "user",
          "query",
          "answer",
          "domain"
        ]
      },
      "minItems": 0,
      "type": "array",
      "uniqueItems": true
    },
    "how_to_implement": {
      "description": "A discussion on how to implement this search, from what needs to be ingested, config files modified, and suggested per site modifications",
      "examples": [
        "To successfully implement this search, you must be ingesting DNS logs, and populating the Network_Resolution data model. Also make sure that the cim_corporate_web_domains and cim_corporate_email_domains lookups are populated with the domains owned by your corporation"
      ],
      "type": "string"
    },
    "id": {
      "description": "The unique identifier for the search",
      "examples": [
        "c096f721-8842-42ce-bfc7-74bd8c72b7c3"
      ],
      "type": "string"
    },
    "known_false_positives": {
      "description": "Describe the known false postives while the analyst builds the baseline.",
      "examples": [
        "Please vet the lookup created by this baseline search."
      ],
      "type": "string"
    },
    "maintainers": {
      "description": "An array of the current maintainers of the Analytic Story.",
      "items": {
        "properties": {
          "company": {
            "description": "Company associated with the person maintaining this search",
            "examples": [
              "Splunk"
            ],
            "type": "string"
          },
          "email": {
            "description": "Email address of the person maintaining this search",
            "examples": [
              "daftpunk@splunk.com"
            ],
            "type": "string"
          },
          "name": {
            "description": "Name of the person maintaining this search",
            "examples": [
              "Daft Punk"
            ],
            "type": "string"
          }
        },
        "required": [
          "name",
          "email",
          "company"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "modification_date": {
      "description": "The date of the most recent modification to the search",
      "examples": [
        "2019-02-14"
      ],
      "type": "string"
    },
    "name": {
      "description": "The name of the search that creates the baseline",
      "examples": [
        "Discover DNS records"
      ],
      "type": "string"
    },
    "original_authors": {
      "description": "A list of the original authors of the search",
      "items": {
        "properties": {
          "company": {
            "description": "Company associated with the person who originally authored the search",
            "examples": [
              "Splunk"
            ],
            "type": "string"
          },
          "email": {
            "description": "Email address of the person who originally authored the search",
            "examples": [
              "daftpunk@splunk.com"
            ],
            "type": "string"
          },
          "name": {
            "description": "Name of the person who originally authored the search",
            "examples": [
              "Daft Punk"
            ],
            "type": "string"
          }
        },
        "required": [
          "name",
          "email",
          "company"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "spec_version": {
      "description": "The version of the detection search specification this manifest follows",
      "examples": [
        "2.0"
      ],
      "type": "integer"
    },
    "type": {
      "description": "The type of baseline",
      "enum": [
        "splunk",
        "phantom",
        "uba"
      ],
      "examples": [
        "splunk"
      ]
    },
    "version": {
      "description": "The version of the search",
      "examples": [
        "1",
        "2"
      ],
      "type": "string"
    }
  },
  "required": [
    "id",
    "creation_date",
    "data_metadata",
    "eli5",
    "known_false_positives",
    "how_to_implement",
    "maintainers",
    "modification_date",
    "original_authors",
    "name",
    "description",
    "type",
    "spec_version",
    "version",
    "baseline"
  ],
  "title": "Baseline Manifest",
  "type": "object"
}

=== splunk/security_content/baselines/previously_seen_user_roles.json
{
  "baseline": {
    "splunk": {
      "schedule": {
        "cron_schedule": "",
        "earliest_time": "-30d@d",
        "latest_time": "-10m@m"
      },
      "search": "sourcetype=aws:cloudtrail eventType=AwsApiCall errorCode=success userIdentity.type=AssumedRole | stats earliest(_time) as earliest latest(_time) as latest by userName eventName | outputlookup previously_seen_api_calls_from_user_roles | stats count"
    }
  },
  "creation_date": "2018-04-01",
  "data_metadata": {
    "data_source": [
      "AWS CloudTrail logs"
    ],
    "data_sourcetypes": [
      "aws:cloudtrail"
    ],
    "providing_technologies": [
      "AWS"
    ]
  },
  "description": "This search looks for successful API calls made by different user roles, then creates a baseline of the earliest and latest times we have encountered this user role. It also returns the name of the API call in our dataset--grouped by user role and name of the API call--that occurred within the last 30 days. In this support search, we are only looking for events where the user identity is Assumed Role.",
  "eli5": "In this support search, we are looking for successful API calls made by user roles within your AWS infrastructure. The intent is to create an initial baseline cache of names of the API calls per security role for the previous 30 days--including the earliest and latest times seen in our dataset--grouped by the value of user role and the name of the API call. It is also worth noting that the role of a particular user is parsed as \"userName\" in the CloudTrail logs.",
  "how_to_implement": "You must install the AWS App for Splunk (version 5.1.0 or later) and Splunk Add-on for AWS (version 4.4.0 or later), then configure your CloudTrail inputs. Please validate the user role entries in `previously_seen_api_calls_from_user_roles.csv`, which is a lookup file created as a result of running this support search.",
  "id": "fc0edc95-fq2c-48b0-9f6f-63da3289fd03",
  "known_false_positives": "",
  "maintainers": [
    {
      "company": "Splunk",
      "email": "bpatel@splunk.com",
      "name": "Bhavin Patel"
    }
  ],
  "modification_date": "2018-04-16",
  "name": "Previously seen API call per user roles in CloudTrail",
  "original_authors": [
    {
      "company": "Splunk",
      "email": "bpatel@splunk.com",
      "name": "Bhavin Patel"
    }
  ],
  "spec_version": 2,
  "type": "splunk",
  "version": "1.0"
}

=== splunk/security_content/baselines/previously_seen_ec2_modifications.json
{
    "baseline": {
        "splunk": {
            "schedule": {
                "cron_schedule": "",
                "earliest_time": "-90d@d",
                "latest_time": "-10m@m"
            },
            "search": "sourcetype=aws:cloudtrail `ec2ModificationAPIs` errorCode=success | spath output=arn userIdentity.arn | stats earliest(_time) as firstTime latest(_time) as lastTime by arn | outputlookup previously_seen_ec2_modifications_by_user | stats count"
        }
    },
    "creation_date": "2018-04-05",
    "data_metadata": {
        "data_source": [
            "AWS CloudTrail logs"
        ],
        "data_sourcetypes": [
            "aws:cloudtrail"
        ],
        "providing_technologies": [
            "AWS"
        ]
    },
    "description": "This search builds a table of previously seen ARNs that have launched a EC2 instance.",
    "eli5": "In this support search, we create a table of the earliest and latest times that an ARN has modified a EC2 instance. The list of APIs that modify an EC2 are defined in the <code>ec2ModificationAPIs</code> macro for ease of use. This table is then outputted to a file.",
    "how_to_implement": "You must install the AWS App for Splunk (version 5.1.0 or later) and Splunk Add-on for AWS version (4.4.0 or later), then configure your CloudTrail inputs. To add or remove APIs that modify an EC2 instance, edit the macro <code>ec2ModificationAPIs</code>.",
    "id": "4d69091b-d975-4267-85df-888bd41034eb",
    "known_false_positives": "",
    "maintainers": [
        {
            "company": "Splunk",
            "email": "davidd@splunk.com",
            "name": "David Dorsey"
        }
    ],
    "modification_date": "2018-04-05",
    "name": "Previously Seen EC2 Modifications By User",
    "original_authors": [
        {
            "company": "Splunk",
            "email": "davidd@splunk.com",
            "name": "David Dorsey"
        }
    ],
    "spec_version": 2,
    "type": "splunk",
    "version": "1.0"
}

=== splunk/security_content/baselines/add_prohibited_processes_to_es.json
{
  "baseline": {
    "splunk": {
      "schedule": {
        "cron_schedule": "",
        "earliest_time": "-30d@d",
        "latest_time": "-10m@m"
      },
      "search": "| inputlookup interesting_processes_lookup | search note!=ESCU* | inputlookup append=T prohibitedProcesses_lookup | fillnull value=* dest dest_pci_domain | fillnull value=false is_required is_secure | fillnull value=true is_prohibited | outputlookup interesting_processes_lookup | stats count"
    }
  },
  "creation_date": "2017-06-27",
  "data_metadata": {
    "data_models": [],
    "data_source": [
      "Splunk Enterprise"
    ],
    "providing_technologies": [
      "Splunk Enterprise Security"
    ]
  },
  "description": "This search takes the existing interesting process table from ES, filters out any existing additions added by ESCU and then updates the table with processes identified by ESCU that should be prohibited on your endpoints.",
  "eli5": "This search outputs the interesting processes lookup table and filters out all processes in the table that haven't already been inserted by ESCU. It then appends to those results all the processes currently identified by ESCU that should be prohibited. Next, it fills in the required fields with processes identified by ESCU, and then writes the results back to the interesting process lookup table. This is done so any new processes identified that should be prohibited will be added to the lookup table without creating any duplicate entries.",
  "how_to_implement": "This search should be run on each new install of ESCU.",
  "id": "251930a5-1451-4428-bb13-eed5775be0ce",
  "known_false_positives": "",
  "maintainers": [
    {
      "company": "Splunk",
      "email": "davidd@splunk.com",
      "name": "David Dorsey"
    }
  ],
  "modification_date": "2017-09-15",
  "name": "Add Prohibited Processes to Enterprise Security",
  "original_authors": [
    {
      "company": "Splunk",
      "email": "davidd@splunk.com",
      "name": "David Dorsey"
    }
  ],
  "spec_version": 2,
  "type": "splunk",
  "version": "1.0"
}

=== splunk/security_content/baselines/approved_aws_service_accounts.json
{
  "baseline": {
    "splunk": {
      "schedule": {
        "cron_schedule": "",
        "earliest_time": "-30d@d",
        "latest_time": "-10m@m"
      },
      "search": "sourcetype=aws:cloudtrail errorCode=success | rename userName as identity | search NOT [inputlookup identity_lookup_expanded | fields identity] | stats count by identity | table identity | outputlookup aws_service_accounts | stats count"
    }
  },
  "creation_date": "2018-03-12",
  "data_metadata": {
    "data_source": [
      "AWS CloudTrail logs"
    ],
    "data_sourcetypes": [
      "aws:cloudtrail"
    ],
    "providing_technologies": [
      "AWS"
    ]
  },
  "description": "This search looks for successful API activity in CloudTrail within the last 30 days, filters out known users from the identity table, and outputs values of users into `aws_service_accounts.csv` lookup file.",
  "eli5": "We first look for all successful CloudTrail API activity caused by types of user accounts and then remove all the events caused by users in the Identity table. This generates a list of accounts--typically service accounts--configured in your AWS environment. We output this list of service accounts to `aws_service_accounts.csv`.",
  "how_to_implement": "You must install the AWS App for Splunk (version 5.1.0 or later) and Splunk Add-on for AWS (version 4.4.0 or later), then configure your CloudTrail inputs. Please validate the service account entires in `aws_service_accounts.csv`, which is a lookup file created as a result of running this support search. Please remove the entries of service accounts that are not legitimate.",
  "id": "fc0edc95-ff2b-48b1-5f6f-63ga3789fd43",
  "known_false_positives": "",
  "maintainers": [
    {
      "company": "Splunk",
      "email": "bpatel@splunk.com",
      "name": "Bhavin Patel"
    }
  ],
  "modification_date": "2018-12-03",
  "name": "Create a list of approved AWS service accounts",
  "original_authors": [
    {
      "company": "Splunk",
      "email": "bpatel@splunk.com",
      "name": "Bhavin Patel"
    }
  ],
  "spec_version": 2,
  "type": "splunk",
  "version": "2.0"
}

=== splunk/security_content/baselines/previously_seen_aws_cross_account_activity.json
{
    "baseline": {
        "splunk": {
            "schedule": {
                "cron_schedule": "",
                "earliest_time": "-30d@d",
                "latest_time": "-10m@m"
            },
            "search": "sourcetype=aws:cloudtrail eventName=AssumeRole | spath output=requestingAccountId path=userIdentity.accountId | spath output=requestedAccountId path=resources{}.accountId | search requestingAccountId=* | where requestingAccountId!=requestedAccountId | stats earliest(_time) as firstTime latest(_time) as lastTime by requestingAccountId, requestedAccountId | outputlookup previously_seen_aws_cross_account_activity | stats count"
        }
    },
    "creation_date": "2018-06-04",
    "data_metadata": {
        "data_source": [
            "AWS CloudTrail logs"
        ],
        "data_sourcetypes": [
            "aws:cloudtrail"
        ],
        "providing_technologies": [
            "AWS"
        ]
    },
    "description": "This search looks for <b>AssumeRole</b> events where the requesting account differs from the requested account, then writes these relationships to a lookup file.",
    "eli5": "In this support search, we look for <b>AssumeRole</b> events where the requesting account is different from the requested account. The first and last times these events are seen are written to a lookup file.",
    "how_to_implement": "You must install the AWS App for Splunk (version 5.1.0 or later) and Splunk Add-on for AWS (version 4.4.0 or later), then configure your CloudTrail inputs. Validate the user name entries in <code>previously_seen_aws_cross_account_activity.csv</code>, a lookup file created by this support search.",
    "id": "1cc22b09-c867-416e-a511-cb36ac44aee2",
    "known_false_positives": "",
    "maintainers": [
        {
            "company": "Splunk",
            "email": "davidd@splunk.com",
            "name": "David Dorsey"
        }
    ],
    "modification_date": "2018-06-04",
    "name": "Previously Seen AWS Cross Account Activity",
    "original_authors": [
        {
            "company": "Splunk",
            "email": "davidd@splunk.com",
            "name": "David Dorsey"
        }
    ],
    "spec_version": 2,
    "type": "splunk",
    "version": "1.0"
}

=== splunk/security_content/baselines/train_dns_query_length.json
{
    "baseline": {
        "splunk": {
            "schedule": {
                "cron_schedule": "",
                "earliest_time": "-31d@d",
                "latest_time": "-1d@d"
            },
            "search": "| tstats `summariesonly` count from datamodel=Network_Resolution by DNS.query DNS.record_type | search DNS.record_type=* | `drop_dm_object_name(\"DNS\")` | eval query_length = len(query) | fit DensityFunction query_length by record_type into dns_query_pdfmodel"
        }
    },
    "creation_date": "2019-05-08",
    "data_metadata": {
        "data_models": [
            "Network_Resolution"
        ],
        "data_source": [
            "DNS"
        ],
        "providing_technologies": [
            "Splunk Stream",
            "Bro"
        ]
    },
    "description": "This search is used to build a Machine Learning Toolkit (MLTK) model to characterize the length of the DNS queries for each DNS record type observed in the environment. By default, the search uses the last 30 days of data to build the model. The model created by this search is then used in the corresponding detection search, which uses it to identify outliers in the length of the DNS query.",
    "eli5": "Create a machine-learning (ML) model to characterize the length of DNS requests seen in your environment to help identify unusually long ones that may be indicative of attacker infrastrucutre or the use of DNS as a command-and-control channel in your environment.",
    "how_to_implement": "To successfully implement this search, you will need to ensure that DNS data is populating the Network_Resolution data model. In addition, you must have the Machine Learning Toolkit (MLTK) version >= 4.2 installed, along with any required dependencies. By default, the search builds the model using the past 30 days of data. You can modify the search window to build the model over a longer period of time, which may give you better results. You may also want to periodically re-run this search to rebuild the model with the latest data. More information on the algorithm used in the search can be found at `https://docs.splunk.com/Documentation/MLApp/4.2.0/User/Algorithms#DensityFunction`.",
    "id": "c914844c-0ff5-4efc-8d44-c063443129ba",
    "known_false_positives": "",
    "maintainers": [
        {
            "company": "Splunk",
            "email": "rvaldez@splunk.com",
            "name": "Rico Valdez"
        }
    ],
    "modification_date": "2019-05-08",
    "name": "Baseline of DNS Query Length - MLTK",
    "original_authors": [
        {
            "company": "Splunk",
            "email": "rvaldez@splunk.com",
            "name": "Rico Valdez"
        }
    ],
    "spec_version": 2,
    "type": "splunk",
    "version": "1.0"
}
